[package]
name = "image_uploader"
version = "0.1.0"
authors = ["Ales Tsurko <ales.tsurko@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "^0.7"
bytes = "^0.4.11"
mime = "^0.3.13"
env_logger = "^0.6.0"
log = "^0.4"
iovec = "^0.1.2"
futures = "^0.1"
serde_json = "^1.0"
